name: Tests

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SKIP_FRONTEND_BUILD: "1"

jobs:
  cargo-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libsystemd-dev
      - name: Create frontend/dist placeholder
        run: mkdir -p crates/web/frontend/dist
      - name: cargo test
        run: cargo test --workspace --all-targets --locked
